use task3

create table post

(id int identity primary key,content nvarchar(100),sharedtime date,userid int, likecount int, isdeleted bit default 0)

INSERT INTO POST (CONTENT,SHAREDTIME,USERID,LIKECOUNT,ISDELETED)
VALUES
('CONTENT1','2022-01-01',1,45,'FALSE'),
('CONTENT2','2022-02-05',2,78,'FALSE'),
('CONTENT3','2022-07-09',3,85,'FALSE'),
('CONTENT4','2022-01-05',4,45,'FALSE')

CREATE TABLE USERR
(ID INT IDENTITY PRIMARY KEY, LOGIN NVARCHAR(100) UNIQUE, PASSWORD NVARCHAR(100), MAIL NVARCHAR (100) UNIQUE)

INSERT INTO USERR(LOGIN,PASSWORD,MAIL)
VALUES
('RESAD','RESAD123','RESAD123@MAIL.RU'),
('ELI','ELI123','ELI123@MAIL.RU'),
('VUSAL','VUSAL123','VUSAL123@MAIL.RU'),
('RAUF','RAUF123','RAUF@MAIL.RU')


CREATE TABLE COMMENT
(ID INT IDENTITY PRIMARY KEY, USERID INT,POSTID INT ,COMMENTCOUNT INT,ISDELETED BIT DEFAULT 0)
INSERT INTO COMMENT(USERID,POSTID,COMMENTCOUNT,ISDELETED)
VALUES
(1,1,14,'FALSE'),
(2,2,11,'FALSE'),
(3,3,43,'FALSE'),
(4,4,56,'FALSE')

CREATE TABLE PEOPLE 
(ID INT IDENTITY PRIMARY KEY, NAME NVARCHAR(100), SURNAME NVARCHAR(100), AGE INT)
INSERT INTO PEOPLE (NAME,SURNAME,AGE)
VALUES
('NESIMI','CEFEROV',33),
('RZA','HACIYEV',18),
('ELNUR','KERIMOV',24),
('NIHAD','ELIYEV',28)





CREATE PROCEDURE USP_NAME
AS
BEGIN
SELECT  COUNT(C.COMMENTCOUNT)'COMMENTCOUNT' FROM POST AS P
JOIN COMMENT AS C
ON C.POSTID=P.ID
GROUP BY C.COMMENTCOUNT

END

EXEC USP_NAME




CREATE TRIGGER INSTEADOFDELET
ON POST
INSTEAD OF DELETE
AS
BEGIN
UPDATE POST SET ISDELETED = 1 WHERE ID = 1
END

DELETE POST
WHERE ID = 1


CREATE TRIGGER INSTEADOFDELETE
ON COMMENT
INSTEAD OF DELETE
AS
BEGIN
UPDATE COMMENT SET ISDELETED = 1 WHERE ID = 1
END

DELETE COMMENT
WHERE ID = 1




create view     VIEWSS AS 
    select          *
    from            POST P            
     JOIN        COMMENT C
    on              c.POSTID = P.ID   
     join       USERR U     
    on              U.ID = C.USERID
